2025-08-03 14:46:05,135 Minimum price: 10, Maximum price: 350
2025-08-03 14:46:05,147 Preparing sklearn pipeline
2025-08-03 14:46:05,147 Fitting
2025-08-03 14:46:05,147 Scoring
Traceback (most recent call last):
  File "/home/dennis-grisham/miniconda3/envs/mlflow-d20df18b17b0c54747eba2677649d2bbc0879a75/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 29, in _check
    check_result = self.check(obj)
  File "/home/dennis-grisham/miniconda3/envs/mlflow-d20df18b17b0c54747eba2677649d2bbc0879a75/lib/python3.10/site-packages/sklearn/pipeline.py", line 51, in check
    getattr(self._final_estimator, attr)
  File "/home/dennis-grisham/miniconda3/envs/mlflow-d20df18b17b0c54747eba2677649d2bbc0879a75/lib/python3.10/site-packages/sklearn/pipeline.py", line 336, in _final_estimator
    estimator = self.steps[-1][1]
IndexError: list index out of range
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/dennis-grisham/D501_Project_1_NYC_Airbnb/src/train_random_forest/run.py", line 291, in <module>
    go(args)
  File "/home/dennis-grisham/D501_Project_1_NYC_Airbnb/src/train_random_forest/run.py", line 81, in go
    r_squared = sk_pipe.score(X_val, y_val)
  File "/home/dennis-grisham/miniconda3/envs/mlflow-d20df18b17b0c54747eba2677649d2bbc0879a75/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 40, in __get__
    self._check(obj, owner=owner)
  File "/home/dennis-grisham/miniconda3/envs/mlflow-d20df18b17b0c54747eba2677649d2bbc0879a75/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 31, in _check
    raise AttributeError(attr_err_msg) from e
AttributeError: This 'Pipeline' has no attribute 'score'